// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: demo2.4

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_event(lv_event_t * e);
void off_event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
