// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: demo2.4

#include "ui.h"
#include <stdio.h>
#include "driver/gpio.h"

void on_event(lv_event_t * e)
{
	// Your code here
	printf("turn on the light\n");
	gpio_set_level(25, 1);
}

void off_event(lv_event_t * e)
{
	// Your code here
	printf("turn off the light\n");
	gpio_set_level(25, 0);
}
